<?php

namespace Tests\Feature;

use App\Models\User;
use Database\Seeders\ServiceSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @covers   \App\Http\Controllers\ServiceController
 */
class ServiceTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed(ServiceSeeder::class);
    }

    public function test_user_can_see_list_of_services()
    {
        $user = $this->create(User::class);
        $this->actingAs($user);


        $this->getJson('api/services')->assertJsonStructure(['data' => [
            [
                'id',
                'title'
            ]
        ]
        ]);
    }
}
